### ISSUE TITLE
NeRF synthetic points

### ISSUE THREAD

**Issue by renhaofan** [seanywang0408/RadianceMapping#2]
Hi, I notice that you mention `Nerf-synthetic points` genertated from [Point-NeRF](https://github.com/Xharlie/pointnerf) 

> 
NeRF-Synthetic: Please download dataset from [NeRF](https://github.com/bmild/nerf) and put the unpacked files in `./data/nerf_synthetic`. To generate point clouds, run [Point-NeRF](https://github.com/Xharlie/pointnerf) and save the point clouds in `./data/pc/nerf.`

However,  [Point-NeRF](https://github.com/Xharlie/pointnerf) env is hard to configure.  So, I utilize the points generated from vanilla-nerf,  but the PSNR is very slow about 15db after training 200k.  I think the coordinate or something different compared with your `./data/pc/nerf.`

**So, Can you share me `./data/pc/nerf` ?**  
Thanks in advance.

**Comment by yizhangphd** [comment]
The point clouds have been uploaded to https://drive.google.com/drive/folders/1qcEk97RgwCAzzmXUTUXCGNsGzwYPicLA
